### ISSUE TITLE
Duplicate of lodash.keysin

### ISSUE THREAD

**Issue by fregante** [dorayx/object-property-names#1]
Good job on the module! I found this when looking for `Object.getALLPropertyNames`

I later realized that lodash has the equivalent of this and thought I'd ping you :)

I think [`_.keysIn`](https://lodash.com/docs#keysIn) matches `getNonNativePropertyNames`

**Comment by dorayx** [comment]
`_.keysIn` does match `getNonNativePropertyNames` but the difference is that this module can retrieve the non-enumerable properties while lodash can only retrieve the enumerable.
